#!/bin/bash

selected=$({ echo ~/dev-env; find -L ~/dev-env ~/repos -mindepth 1 -maxdepth 1 -type d; } | fzf)
if [[ -z "$selected" ]]; then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "----")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		exec tmux attach -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}


if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
else
	echo "4"
	tmux new-session -ds $selected_name -c $selected
	tmux send-keys -t $selected_name "ready-tmux" Enter
	switch_to
fi
