[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"

[font.normal]
family = "Hack Nerd Font"

[keyboard]
bindings = [
    # Remap Hyper-Space to M-Space
    { key = "Space", mods = "Command | Option | Control", chars = "\u001b " },
    { key = "h", mods = "Command | Option | Control", chars = "\u001bh" },
    { key = "j", mods = "Command | Option | Control", chars = "\u001bj" },
    { key = "k", mods = "Command | Option | Control", chars = "\u001bk" },
    { key = "l", mods = "Command | Option | Control", chars = "\u001bl" },
    { key = "f", mods = "Command | Option | Control", chars = "\u001bf" },
    { key = ";", mods = "Command | Option | Control", chars = "\u001b;" },
    { key = "'", mods = "Command | Option | Control", chars = "\u001b'" },
]
